
set(MCU_TYPE TEST)

set(MCU_LIB_NAME TEST_LIB)

set(MCU_MAJOR_VERSION_LIB 1)

set(MCU_MINOR_VERSION_LIB 00)

set(FULL_NAME_MCU_LIB ${MCU_TYPE}-${MCU_LIB_NAME}-${MCU_MAJOR_VERSION_LIB}-${MCU_MINOR_VERSION_LIB} )

FILE(GLOB COPY_OBJECT_FROM_LIB "${MCU_LIB_PATH}/*.h")