
set(MCU_TYPE TEST)

set(MCU_LIB_NAME TEST_LIB)

set(MCU_MAJOR_VERSION_LIB 1)

set(MCU_MINOR_VERSION_LIB 00)

set(FULL_NAME_MCU_LIB ${MCU_TYPE}-${MCU_LIB_NAME}-${MCU_MAJOR_VERSION_LIB}-${MCU_MINOR_VERSION_LIB} )

FILE(GLOB COPY_SOURCE_FROM_LIB "${CMAKE_CURRENT_LIST_DIR}/*.h")
FILE(GLOB COPY_DESCRIPTION_FROM_LIB "${CMAKE_CURRENT_LIST_DIR}/README.txt")

set(CONF_SOURCE ${CMAKE_CURRENT_LIST_DIR}/conf.cpp)

set(ADIN_OBJECT_FILE ${CMAKE_CURRENT_LIST_DIR}/build/${MCU_TYPE}.adin.o)

add_custom_command(OUTPUT ${ADIN_OBJECT_FILE}
                   COMMAND make all
                   WORKING_DIRECTORY ${CMAKE_CURRENT_LIST_DIR}
                   COMMENT "---------------- Generating ADIN IR ----------------"
)
