
if(DEFINED REMCU_PREBUILD_CONFIG_FILE)
      include(REMCU_PREBUILD_CONFIG_FILE)
endif()

set(BUILD_IR_TEST_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/IrTest)

set(IR_TEST_OBJECT_FILE ${BUILD_IR_TEST_DIRECTORY}/IrTest.adin.o)

set(IR_TEST_MAKE_ARGUMENTS TARGET_MK=${MCU_INCLUDE_MK_FILE})
list(APPEND IR_TEST_MAKE_ARGUMENTS MCU_UTIL_PATH=${MCU_UTIL_PATH})
list(APPEND IR_TEST_MAKE_ARGUMENTS CMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE})
list(APPEND IR_TEST_MAKE_ARGUMENTS LLVM_ADIN_PATH=${LLVM_ADIN_PATH})
list(APPEND IR_TEST_MAKE_ARGUMENTS CROSS_MK_FILE=${CROSS_MK_FILE})
list(APPEND IR_TEST_MAKE_ARGUMENTS CLANG_PATH=${CLANG_PATH})

add_custom_target( IR_TEST_OBJ
                   COMMAND make all
                   ${IR_TEST_MAKE_ARGUMENTS}
                   OUTPUT=${IR_TEST_OBJECT_FILE}
                   BUILD_DIRECTORY=${BUILD_IR_TEST_DIRECTORY}
                   WORKING_DIRECTORY ${CMAKE_CURRENT_LIST_DIR}
                   COMMENT "---------------- Generating IR Test ----------------"
                    BYPRODUCTS ${IR_TEST_OBJECT_FILE}
)
