
if(WIN32)
	set(ARCHIVE_COMMAND zip -r ${FULL_ARCHIVE_NAME}.zip)
	set(ARCHIVE_FORMAT zip)
	set(ARCHIVE_SUFFIX zip)
else()
	set(ARCHIVE_COMMAND tar -cf ${FULL_ARCHIVE_NAME}.tar)
	set(ARCHIVE_FORMAT gnutar)
	set(ARCHIVE_SUFFIX tar)
endif()