set(FULL_NAME_MCU_LIB ${MCU_TYPE}-${MCU_LIB_NAME}-${MCU_MAJOR_VERSION_LIB}-${MCU_MINOR_VERSION_LIB} )

if(NOT CONF_SOURCE)
    set(CONF_SOURCE ${CMAKE_CURRENT_SOURCE_DIR}/conf.cpp)
endif()

if(NOT MAKEFILE_DIR)
    set(MAKEFILE_DIR ${CMAKE_CURRENT_SOURCE_DIR})
endif()

set(CMAKE_MODULE_PATH ${REMCU_VM_PATH}/cmake)

include(McuCommon)

set(MCU_MAKE_ARGUMENTS TARGET_MK=${MCU_INCLUDE_MK_FILE})
list(APPEND MCU_MAKE_ARGUMENTS MCU_UTIL_PATH=${MCU_UTIL_PATH})
list(APPEND MCU_MAKE_ARGUMENTS OUTPUT=${MCU_OBJECT_FILE})
list(APPEND MCU_MAKE_ARGUMENTS CMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE})
list(APPEND MCU_MAKE_ARGUMENTS BUILD_DIRECTORY=${BUILD_DIRECTORY})
list(APPEND MCU_MAKE_ARGUMENTS DEVICE=${MCU_TYPE})
list(APPEND MCU_MAKE_ARGUMENTS MCU_LIB_NAME=${MCU_LIB_NAME})
list(APPEND MCU_MAKE_ARGUMENTS MCU_MAJOR_VERSION_LIB=${MCU_MAJOR_VERSION_LIB})
list(APPEND MCU_MAKE_ARGUMENTS MCU_SDK_PATH=${MCU_SDK_PATH})
list(APPEND MCU_MAKE_ARGUMENTS LLVM_ADIN_PATH=${LLVM_ADIN_PATH})
list(APPEND MCU_MAKE_ARGUMENTS CROSS_MK_FILE=${CROSS_MK_FILE})
list(APPEND MCU_MAKE_ARGUMENTS CLANG_PATH=${CLANG_PATH})

add_custom_target( MCU_LIB
                   COMMAND make all
                   ${MCU_MAKE_ARGUMENTS}
                   WORKING_DIRECTORY ${MAKEFILE_DIR}
                   COMMENT "---------------- Generating ADIN IR ----------------"
                   BYPRODUCTS ${MCU_OBJECT_FILE}
)

include(shared)
