include(${CMAKE_ROOT}/Modules/ExternalProject.cmake)


set(CMAKE_ARGS -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE})
list(APPEND CMAKE_ARGS -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE})
list(APPEND CMAKE_ARGS -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER})
list(APPEND CMAKE_ARGS -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER})
list(APPEND CMAKE_ARGS -DCMAKE_MAKE_PROGRAM=${CMAKE_MAKE_PROGRAM})
list(APPEND CMAKE_ARGS -DDESTINATION_DIR_NAME_PREFIX=${DESTINATION_DIR_NAME_PREFIX})

if(REMCU_OUTPUT_DIR)
  list(APPEND CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${REMCU_OUTPUT_DIR})
else()
  set(OUT ${CMAKE_BINARY_DIR}/output)
  list(APPEND CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${OUT})
  message("No set REMCU_OUTPUT_DIR variable")
  message("You can find remcu library and the test artifact by path: ${OUT}")
endif(REMCU_OUTPUT_DIR)


if (CMAKE_BUILD_TYPE STREQUAL "Debug")
  set(INSTALL_COMMAND "")
else()
  set(INSTALL_COMMAND "ls -la")
endif()